### ISSUE TITLE
Unexpected token 

### ISSUE THREAD

**Issue by timoline** [basst85/NextRemoteJs#2]
Getting this error, any idea?

const getSession = async () => {
                         ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nextremotejs@1.0.0 start: `node index.js`
npm ERR! Exit status 1

**Comment by timoline** [comment]
Nevermind, it's working now.
Updated to latest node.js

many rhx
